name: travel_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.2

  #network handling
  dio: ^5.1.0

  #responsive_flutter
  sizer: ^2.0.15

  #routing
  go_router: ^6.5.0
  get: ^4.6.5
  flutter_avif: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/sora/Sora-Regular.ttf
        - asset: assets/fonts/sora/Sora-SemiBold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
